const { app, BaseWindow, WebContentsView, BrowserWindow, ipcMain, clipboard, dialog } = require('electron');
const path = require('path');
const fs = require('fs');

let mainWindow;
let toolbarView;
let browserView;

const TOOLBAR_HEIGHT = 170;

function createWindow() {
  mainWindow = new BaseWindow({
    width: 1280,
    height: 900,
    minWidth: 800,
    minHeight: 600,
    title: 'Prompt Keeper',
  });

  // Toolbar view — top portion
  toolbarView = new WebContentsView({
    webPreferences: {
      preload: path.join(__dirname, 'preload-toolbar.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  mainWindow.contentView.addChildView(toolbarView);
  toolbarView.webContents.loadFile(path.join(__dirname, 'toolbar', 'index.html'));

  // Browser view — bottom portion (the embedded browser)
  browserView = new WebContentsView({
    webPreferences: {
      preload: path.join(__dirname, 'preload-browser.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  mainWindow.contentView.addChildView(browserView);
  browserView.webContents.loadURL('https://www.google.com');

  // Layout both views
  function layoutViews() {
    const { width, height } = mainWindow.getContentBounds();
    toolbarView.setBounds({ x: 0, y: 0, width, height: TOOLBAR_HEIGHT });
    browserView.setBounds({ x: 0, y: TOOLBAR_HEIGHT, width, height: height - TOOLBAR_HEIGHT });
  }

  layoutViews();
  mainWindow.on('resize', layoutViews);

  // Update toolbar when the browser navigates to a new page
  browserView.webContents.on('did-navigate', (event, url) => {
    toolbarView.webContents.send('url-changed', url);
  });
  browserView.webContents.on('did-navigate-in-page', (event, url) => {
    toolbarView.webContents.send('url-changed', url);
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── IPC Handlers ──

ipcMain.handle('clipboard-write', (_event, text) => {
  clipboard.writeText(text);
});

ipcMain.handle('navigate', (_event, url) => {
  if (!/^https?:\/\//i.test(url)) url = 'https://' + url;
  browserView.webContents.loadURL(url);
});

ipcMain.handle('browser-back', () => {
  if (browserView.webContents.canGoBack()) browserView.webContents.goBack();
});

ipcMain.handle('browser-forward', () => {
  if (browserView.webContents.canGoForward()) browserView.webContents.goForward();
});

// Generate PDF using a hidden BrowserWindow + printToPDF (no external libraries)
ipcMain.handle('export-pdf', async (_event, prompts) => {
  const sessionDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const artist = prompts[0]?.artist || 'Unknown';

  // Build an HTML document for the PDF
  const rows = prompts.map((p) =>
    `<tr><td>${escapeHtml(p.timestamp)}</td><td>${escapeHtml(p.tool)}</td><td>${escapeHtml(p.prompt)}</td></tr>`
  ).join('\n');

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif; padding: 30px; color: #222; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .meta { font-size: 12px; color: #555; margin-bottom: 2px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { background: #f0f0f0; text-align: left; font-size: 11px; padding: 6px 8px; border: 1px solid #ccc; }
  td { font-size: 10px; padding: 5px 8px; border: 1px solid #ddd; vertical-align: top; }
  tr:nth-child(even) { background: #fafafa; }
  .footer { margin-top: 20px; font-size: 9px; color: #999; text-align: center; }
</style></head><body>
  <h1>Prompt Keeper &mdash; Session Log</h1>
  <p class="meta">Date: ${escapeHtml(sessionDate)}</p>
  <p class="meta">Artist: ${escapeHtml(artist)}</p>
  <p class="meta">Total prompts: ${prompts.length}</p>
  <table>
    <thead><tr><th style="width:120px">Timestamp</th><th style="width:90px">Tool</th><th>Prompt</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by Prompt Keeper</div>
</body></html>`;

  // Create a hidden window to render the HTML and print to PDF
  const pdfWindow = new BrowserWindow({ show: false, width: 800, height: 600 });
  await pdfWindow.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html));

  const pdfBuffer = await pdfWindow.webContents.printToPDF({
    pageSize: 'A4',
    margins: { top: 0.4, bottom: 0.4, left: 0.4, right: 0.4 },
    printBackground: true,
  });

  pdfWindow.close();

  // Show save dialog
  const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
    defaultPath: `prompt-session-${new Date().toISOString().slice(0, 10)}.pdf`,
    filters: [{ name: 'PDF', extensions: ['pdf'] }],
  });
  if (canceled || !filePath) return { saved: false };

  fs.writeFileSync(filePath, pdfBuffer);
  return { saved: true };
});

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── App lifecycle ──

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  if (!mainWindow) createWindow();
});
